require("core.plugins")
require("core.options")
require("core.colors")
require("core.nvimtree")
require("core.lsp")
require("core.cmp")
require("core.statusline")
require("core.keymaps")
require("core.autocmds")

